version: '2'

services:
  grafana:
    build: grafana/
    ports:
      - 3000:3000
    network_mode: 'host'
    volumes:
      - grafana_data:/var/lib/grafana
  mongodb-proxy:
    build: mongodb-proxy/
    ports:
      - 3333:3333
    network_mode: 'host'
volumes:
  grafana_data:
